[versions]
kotlin = "2.3.10"
dataframe = "1.0.0-Beta4"
kandy = "0.8.3"
ktlint-gradle = "14.0.1"
ktlint = "1.8.0"

[libraries]
dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "dataframe" }
kandy = { module = "org.jetbrains.kotlinx:kandy-lets-plot", version.ref = "kandy" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }

# The Kotlin DataFrame Compiler plugin is the same version as the Kotlin plugin.
kotlin-dataframe = { id = "org.jetbrains.kotlin.plugin.dataframe", version.ref = "kotlin" }
